language: c
cache: ccache
compiler: gcc
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - figlet
    - frei0r-plugins-dev
    - libfontconfig-dev
    - libfribidi-dev
    - libmp3lame-dev
    - libopencore-amrnb-dev
    - libopencore-amrwb-dev
    - libopenjpeg-dev
    - libopus-dev
    - libsoxr-dev
    - libspeex-dev
    - libtheora-dev
    - libvorbis-dev
    - libvo-amrwbenc-dev
    - libwebp-dev
    - libx264-dev
    - libxvidcore-dev
    - texinfo
    - yasm
script: "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: d73dh08dGNowoKa+C4Z3wGuIIfXMy9vkZypvo/8RAsnqSRRzsRiIby48y3auVkpG7jII28puNRspnrm4fnWmnBKgRUlCH8Jmy0VExiiIZdc0Ta7bxR8rwni8W6O83fHfXQ4WcYnWJKhrY3w6rwcMdQRzBEvddccYXa/C0pU9Iw+JVvKG9nvd9NaYjZgAvdw3Xlm6G4Q5xYQYB2lnnJDrLeO1HGNUGs5+M6KYnalZC9kdJ/QlqGL7QuqO3XRCRlGxiy9LEI4tueKYO3yYNWfuUmlT77q65/ANPUDWSbFpPFplwVMD3UkkfI4EysxkoFYci4VQA+O6251Ovtt2DxFYBhW3M57jbmxhKXZNTch/hYvICmWksD8zWSCcGzT7hJU/q/ec59sszEey7KmYViO8wGdruruDknLHiOuxhmqW+81iQJOrGrfHd6oRQM0MPymK5+4h96LbH2J/7O7gitwkRZQFcON5c8fUPm9+ffVOrfHk1/0AZT0DVyESzLqA2+Tgk+qSliWYogqBg7CSKRaPpZ+xmvb3UQlVDPt0rPHTK/4nkkOOkMIOV/GAw05fNF3YvuTWbk/8ZUua9oAWE0vuEuYDy77kwMGNbfFjrVgVP0W6HZy9q0JuwwVg2gKzyfjcvm0e9I6amlODRCmumsWeYFAiHjIlgZl2usoFkiO9f6w=
  file: ffmpeg-build-lambda.tar.gz
  skip_cleanup: true
  on:
    tags: true
