language: c
compiler: gcc
script: ./build.sh
dist: trusty
sudo: false
addons:
  apt:
    sources:
#    - debian-sid
    packages:
    - libass-dev
    - libfdk-aac-dev
    - libmp3lame-dev
    - libopus-dev
    - libtheora-dev
    - libvorbis-dev
    - libx264-dev
    - libxvidcore-dev
    - texinfo
    - yasm
