language: c
cache: ccache
compiler: gcc
dist: trusty
sudo: required
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "barrett.harber@gmail.com"
addons:
  apt:
    packages:
    - figlet
    - frei0r-plugins-dev
    #- libass-dev
    - libfontconfig-dev
    - libfribidi-dev
    - libmp3lame-dev
    - libopencore-amrnb-dev
    - libopencore-amrwb-dev
    - libopenjpeg-dev
    - libopus-dev
    - libsoxr-dev
    - libspeex-dev
    - libtheora-dev
    - libvorbis-dev
    - libvo-amrwbenc-dev
    - libwebp-dev
    - libx264-dev
    - libxvidcore-dev
    - texinfo
    - yasm
before_install:
- openssl aes-256-cbc -K $encrypted_db3a50dc7bb3_key -iv $encrypted_db3a50dc7bb3_iv -in deploy_key.enc -out deploy_key -d
- git config user.name "Travis CI"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
script: ./build.sh
deploy:
  provider: releases
  api_key:
    secure: HAcyIT0r9NSo5jmfPK3ce/U30BGXwKgrz+4f7usrkyJFYHvQW8fHgxIdrkJVEzQfsFtkAkAnELKkK2+F0hMXccuUlWoH7qWxQxmTor2Kl2YVin5V+lqlI4qGyOlJ05eI5MSH+dQ3ktF8szXtxPjTuVPOTjw+DFqLExhxFGLwZRT8J1OvLkgtKYXYO44FG4T3x3MGfRySU6+x5FNPoucKGU7CQNEOssKRRupSgCwjRNmTrtETe+NZRvncSxijDcpND1j63PCOtmyEPuESFzUHj97ogrMPqK1dsplJ2WtsIjLtdShpSx9e18L8Eu3FE/T8AZUlAUDlMRdOjgEqJNgvMAHvnWmqdF2ZLqI8QG4gqh8ijXscCseS5CyU5erB7OgdAbsEelH2seYDj0VoijHpUPke1XCex8IDm5Eh3hb/oj0ag6tnh7tTu8imMItYhZuGncTOxL3f9mEvXYRQnppN677asgnMLfli17wtRvZjn3iT+uKDO1gGifRRS2ldHX2JSQvcdxBw77+/exPkGaR95Q/2l1zwV9fX9P9L/Ung/iSzRFI6pIMQ25khmRn3XTH6rCms5bKD4a8gOdQYAD3gCFWCLScb0Gw63Rnobhlo5W6k9lblqNoBCoWFSlxTkv8coqK6j9i65odtHQU79Nqpf2wZAJmwlZpcEdhQ5PdiLrY=
  file: ffmpeg-build-lambda.tar.gz
  skip_cleanup: true
  on:
    tags: true
